/*
 * Battlesnake Engine API
 *
 * This is the api of the Battlesnake game engine. See battlesnake.io for details.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EngineDeathCause struct {
	// this records how the snake died, and is one of the 4 possible enum values
	Cause string `json:"Cause,omitempty"`
	// this is the turn that the snake died on
	Turn int32 `json:"Turn,omitempty"`
}
