/*
 * Battlesnake Engine API
 *
 * This is the api of the Battlesnake game engine. See battlesnake.io for details.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EngineCreateRequest struct {
	Width int32 `json:"width"`
	Height int32 `json:"height"`
	Food int32 `json:"food"`
	Snakes []EngineSnakeOptions `json:"snakes"`
}
