/*
 * Battlesnake Snake API
 *
 * Battlesnake participants implement this webhook API to power their snake. See battlesnake.io for details.
 *
 * API version: 2018.03.beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SnakeSnakeRequest struct {
	Game SnakeGame `json:"game,omitempty"`
	Turn int32 `json:"turn,omitempty"`
	Board SnakeBoard `json:"board,omitempty"`
	You SnakeSnake `json:"you,omitempty"`
}
