/*
 * Battlesnake Snake API
 *
 * Battlesnake participants implement this webhook API to power their snake. See battlesnake.io for details.
 *
 * API version: 2018.03.beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SnakeSnake struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Health int32 `json:"health,omitempty"`
	Body []SnakeCoords `json:"body,omitempty"`
}
