/*
 * Battlesnake Snake API
 *
 * Battlesnake participants implement this webhook API to power their snake. See battlesnake.io for details.
 *
 * API version: 2018.03.beta
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package snakemodel

type Board struct {
	Height int32 `json:"height"`
	Width int32 `json:"width"`
	Food []Coords `json:"food"`
	// A list of snakes that are still alive
	Snakes []Snake `json:"snakes"`
}
