/*
 * Battlesnake Engine API
 *
 * This is the api of the Battlesnake game engine. See battlesnake.io for details.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package enginemodel

type Game struct {
	ID string `json:"ID"`
	Status string `json:"Status"`
	Width int32 `json:"Width"`
	Height int32 `json:"Height"`
	SnakeTimeout int32 `json:"SnakeTimeout"`
}
