/*
 * Battlesnake Engine API
 *
 * This is the api of the Battlesnake game engine. See battlesnake.io for details.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package enginemodel

type Game struct {
	ID string `json:"ID,omitempty"`
	Status string `json:"Status,omitempty"`
	Width int32 `json:"Width,omitempty"`
	Height int32 `json:"Height,omitempty"`
	SnakeTimeout int32 `json:"SnakeTimeout,omitempty"`
}
