/*
 * Battlesnake Engine API
 *
 * This is the api of the Battlesnake game engine. See battlesnake.io for details.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package enginemodel

type Snake struct {
	ID string `json:"ID,omitempty"`
	Name string `json:"Name,omitempty"`
	URL string `json:"URL,omitempty"`
	Body []Point `json:"Body,omitempty"`
	Health int32 `json:"Health,omitempty"`
	Death DeathCause `json:"Death,omitempty"`
	// the hex code of the color of the snake
	Color string `json:"Color,omitempty"`
}
