/*
 * Battlesnake Engine API
 *
 * This is the api of the Battlesnake game engine. See battlesnake.io for details.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package enginemodel

type Snake struct {
	ID string `json:"ID"`
	Name string `json:"Name"`
	URL string `json:"URL"`
	Body []Point `json:"Body"`
	Health int32 `json:"Health"`
	Death DeathCause `json:"Death"`
	// the hex code of the color of the snake
	Color string `json:"Color"`
	// the vector head to display, list here https://github.com/battlesnakeio/board/tree/master/public/images/snake/head
	HeadType string `json:"HeadType"`
	// the vector tail to display, list here https://github.com/battlesnakeio/board/tree/master/public/images/snake/tail
	TailType string `json:"TailType"`
}
