name: Release
on:
  release:
    types: [published]
    branches: [main]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Release to AWS ECR
      uses: BattlesnakeOfficial/action-release-to-aws-ecr@main
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
